up:
	docker-compose up -d

re-build:
	docker-compose up -d --build

exec:
	docker-compose exec python-smartread-api-docs sh

run:
	docker-compose exec python-smartread-api-docs sh -c "cd app && python app.py"

list-package:
	docker-compose exec python-smartread-api-docs pip list 