version: '3'
services:
    python-docs-w3:
        build: .
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
            - "8000:8000"
        volumes:
            - .:/app
