up:
	docker-compose up

re-build:
	docker-compose up -d --build

exec:
	docker-compose exec python-docs-w3 sh

run:
	docker-compose exec python-docs-w3 sh -c "cd app && python app.py"

list-package:
	docker-compose exec python-docs-w3 pip list 