up:
	docker-compose up

re-build:
	docker-compose up -d --build

exec:
	docker-compose exec python-vitural-assistant sh

run:
	docker-compose exec python-vitural-assistant sh -c "cd app && python app.py"

list-package:
	docker-compose exec python-vitural-assistant pip list 